### PR TITLE
Add React Native presentation

### PR DESCRIPTION
**Pull request by pesterhazy**
For further questions, reach me at `@pesterhazy` on twitter

### CODE REVIEW

**Comment by xhr15** [comment]
Thanks @pesterhazy, with your permission, I would move this talk to the January meetup as December is already full (fast that was)

Cheers,

Chris

**Comment by pesterhazy** [comment]
Sounds good. Which day in January will that be?

**Comment by xhr15** [comment]
Current planning says it's going to be on January 23rd

**Comment by pesterhazy** [comment]
Sounds good

**Comment by xhr15** [comment]
Hey @pesterhazy, could you please rebase?

**Comment by pesterhazy** [comment]
@xhr15 done

**Comment by xhr15** [comment]
Great!

**Pull request merged**
