### PR TITLE
January talk proposal: "Code splitting with Webpack: alternative approach to route-based chunking"

### PR DESCRIPTION
**Pull request by sejoker**

### CODE REVIEW

**Comment by xhr15** [comment]
Hey @sejoker, could you please rebase?

**Comment by xhr15** [comment]
Hey @sejoker, are you planning on canceling the talk?

**Comment by sejoker** [comment]
I can do the talk only in January. I checked 2 slots already taken for this
month meetup.

**Comment by xhr15** [comment]
Yes, but there are three. So yours is still waiting for you :)

**Comment by xhr15** [comment]
Shall we reopen this? :)

**Comment by sejoker** [comment]
I thought I have reserved the first slot back in December :) I would be happy to present as the first or the second speaker,  but as you said the first 2 slots are already taken.

**Comment by xhr15** [comment]
Have a look here:

bildschirmfoto 2017-01-10 um 11 25 45

Your slot (the second) is still free for you. Would you like to take it? It's your's since December :)

**Comment by xhr15** [comment]
You would only need to rebase your PR

**Comment by sejoker** [comment]
thanks, will do shortly

**Comment by sejoker** [comment]
rebased it here: https://github.com/reactjs-berlin/reactjs.berlin/pull/19

**Pull request closed without merging**
